#!/usr/bin/bash
function get_youtube_id() {
  local url="$1"
  local id
  id=$(echo "$url" | sed -n 's/.*youtube.com\/watch?v=\([^&]*\)\(&.*\)\{0,1\}$/\1/p')
  echo "$id"
}

if [ -n "$1" ]; then
  if [ ! -f "$HOME/.cache/douga" ]; then
    echo "Creating douga file..."
    touch "$HOME/.cache/douga"
  fi

  future_date=$(date '+%Y-%m-%d' -d "+1 days")
  echo "$future_date 1 $(get_youtube_id $1)" >> "$HOME/.cache/douga"
  echo "Added '$1' to douga file."
  exit
fi

print_today_lines() {
  current_date=$(date '+%Y-%m-%d')
  list=""
  while IFS= read -r line; do
    if [[ "$line" == *"$current_date"* ]]; then
      # Print the original line
      list=$list,$(echo "$line" | cut -d" " -f3-)

      # Split the line into an array of words
      words=($line)

      # Extract the number from the second word and multiply by 2
      num=$((${words[1]} * 2))
      if [[ $((${words[1]} * 2)) -eq 0 ]];then
          num=1
      fi

      # Add the modified number to the date in the first word
      new_date=$(date '+%Y-%m-%d' -d "$current_date + $num days")
      words[0]=$new_date
      words[1]=$num

      # Join the modified words back into a single line
      new_line="${words[@]}"

      # Write the modified line back to the file
      sed -i "s|$line|$new_line|" "$HOME/.cache/douga"

      # Print the modified line
    fi
  done < "$HOME/.cache/douga"

  if [[ $list != "" ]]
    then
  echo https://www.youtube.com/watch_videos?video_ids=$(echo $list | cut -c 2-) 
  librewolf --new-tab https://www.youtube.com/watch_videos?video_ids=$(echo $list | cut -c 2-) 
  fi
}

print_today_lines
